/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * skill object
 */
export interface GetCharactersCharacterIdSkillsSkill {
    /**
     * current_skill_level integer
     */
    current_skill_level?: number;

    /**
     * skill_id integer
     */
    skill_id?: number;

    /**
     * skillpoints_in_skill integer
     */
    skillpoints_in_skill?: number;

}
