/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * recipient object
 */
export interface GetCharactersCharacterIdMailMailIdRecipient {
    /**
     * recipient_id integer
     */
    recipient_id: number;

    /**
     * recipient_type string
     */
    recipient_type: GetCharactersCharacterIdMailMailIdRecipient.RecipientTypeEnum;

}
export namespace GetCharactersCharacterIdMailMailIdRecipient {
    export enum RecipientTypeEnum {
        Alliance = <any> 'alliance',
        Character = <any> 'character',
        Corporation = <any> 'corporation',
        MailingList = <any> 'mailing_list'
    }
}
