/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdOk {
    /**
     * id of alliance that corporation is a member of, if any
     */
    alliance_id?: number;

    /**
     * ceo_id integer
     */
    ceo_id: number;

    /**
     * corporation_description string
     */
    corporation_description: string;

    /**
     * the full name of the corporation
     */
    corporation_name: string;

    /**
     * creation_date string
     */
    creation_date?: Date;

    /**
     * creator_id integer
     */
    creator_id: number;

    /**
     * faction string
     */
    faction?: GetCorporationsCorporationIdOk.FactionEnum;

    /**
     * member_count integer
     */
    member_count: number;

    /**
     * tax_rate number
     */
    tax_rate: number;

    /**
     * the short name of the corporation
     */
    ticker: string;

    /**
     * url string
     */
    url: string;

}
export namespace GetCorporationsCorporationIdOk {
    export enum FactionEnum {
        Minmatar = <any> 'Minmatar',
        Gallente = <any> 'Gallente',
        Caldari = <any> 'Caldari',
        Amarr = <any> 'Amarr'
    }
}
