/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * jump_clone object
 */
export interface GetCharactersCharacterIdClonesJumpClone {
    /**
     * implants array
     */
    implants?: Array<number>;

    /**
     * location_id integer
     */
    location_id?: number;

    /**
     * location_type string
     */
    location_type?: GetCharactersCharacterIdClonesJumpClone.LocationTypeEnum;

}
export namespace GetCharactersCharacterIdClonesJumpClone {
    export enum LocationTypeEnum {
        Station = <any> 'station',
        Structure = <any> 'structure'
    }
}
