/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * alliance object
 */
export interface GetCorporationsCorporationIdAlliancehistoryAlliance {
    /**
     * alliance_id integer
     */
    alliance_id: number;

    /**
     * True if the alliance has been deleted
     */
    is_deleted: boolean;

}
