/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetCharactersCharacterIdPlanets200Ok {
    /**
     * last_update string
     */
    last_update: Date;

    /**
     * num_pins integer
     */
    num_pins: number;

    /**
     * owner_id integer
     */
    owner_id: number;

    /**
     * planet_id integer
     */
    planet_id: number;

    /**
     * planet_type string
     */
    planet_type: GetCharactersCharacterIdPlanets200Ok.PlanetTypeEnum;

    /**
     * solar_system_id integer
     */
    solar_system_id: number;

    /**
     * upgrade_level integer
     */
    upgrade_level: number;

}
export namespace GetCharactersCharacterIdPlanets200Ok {
    export enum PlanetTypeEnum {
        Temperate = <any> 'temperate',
        Barren = <any> 'barren',
        Oceanic = <any> 'oceanic',
        Ice = <any> 'ice',
        Gas = <any> 'gas',
        Lava = <any> 'lava',
        Storm = <any> 'storm',
        Plasma = <any> 'plasma'
    }
}
