/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdStructures200Ok {
    /**
     * ID of the corporation that owns the structure
     */
    corporation_id: number;

    /**
     * This week's vulnerability windows, Monday is day 0
     */
    current_vul: Array<models.GetCorporationsCorporationIdStructuresCurrentVul>;

    /**
     * Date on which the structure will run out of fuel
     */
    fuel_expires?: Date;

    /**
     * Next week's vulnerability windows, Monday is day 0
     */
    next_vul: Array<models.GetCorporationsCorporationIdStructuresNextVul>;

    /**
     * The id of the ACL profile for this citadel
     */
    profile_id: number;

    /**
     * Contains a list of service upgrades, and their state
     */
    services?: Array<models.GetCorporationsCorporationIdStructuresService>;

    /**
     * Date at which the structure will move to it's next state
     */
    state_timer_end?: Date;

    /**
     * Date at which the structure entered it's current state
     */
    state_timer_start?: Date;

    /**
     * The Item ID of the structure
     */
    structure_id: number;

    /**
     * The solar system the structure is in
     */
    system_id: number;

    /**
     * The type id of the structure
     */
    type_id: number;

    /**
     * Date at which the structure will unanchor
     */
    unanchors_at?: Date;

}
