/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * item object
 */
export interface GetKillmailsKillmailIdKillmailHashItem {
    /**
     * flag integer
     */
    flag: number;

    /**
     * item_type_id integer
     */
    item_type_id: number;

    /**
     * quantity_destroyed integer
     */
    quantity_destroyed?: number;

    /**
     * quantity_dropped integer
     */
    quantity_dropped?: number;

    /**
     * singleton integer
     */
    singleton: number;

}
