/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetMarketsRegionIdOrders200Ok {
    /**
     * duration integer
     */
    duration: number;

    /**
     * is_buy_order boolean
     */
    is_buy_order: boolean;

    /**
     * issued string
     */
    issued: Date;

    /**
     * location_id integer
     */
    location_id: number;

    /**
     * min_volume integer
     */
    min_volume: number;

    /**
     * order_id integer
     */
    order_id: number;

    /**
     * price number
     */
    price: number;

    /**
     * range string
     */
    range: GetMarketsRegionIdOrders200Ok.RangeEnum;

    /**
     * type_id integer
     */
    type_id: number;

    /**
     * volume_remain integer
     */
    volume_remain: number;

    /**
     * volume_total integer
     */
    volume_total: number;

}
export namespace GetMarketsRegionIdOrders200Ok {
    export enum RangeEnum {
        Station = <any> 'station',
        Region = <any> 'region',
        Solarsystem = <any> 'solarsystem',
        _1 = <any> '1',
        _2 = <any> '2',
        _3 = <any> '3',
        _4 = <any> '4',
        _5 = <any> '5',
        _10 = <any> '10',
        _20 = <any> '20',
        _30 = <any> '30',
        _40 = <any> '40'
    }
}
