/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * participant object
 */
export interface GetSovereigntyCampaignsParticipant {
    /**
     * alliance_id integer
     */
    alliance_id: number;

    /**
     * score number
     */
    score: number;

}
