/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetUniverseSystemsSystemIdOk {
    /**
     * The constellation this solar system is in
     */
    constellation_id: number;

    /**
     * name string
     */
    name: string;

    /**
     * planets array
     */
    planets: Array<models.GetUniverseSystemsSystemIdPlanet>;

    position?: models.GetUniverseSystemsSystemIdPosition;

    /**
     * security_class string
     */
    security_class?: string;

    /**
     * security_status number
     */
    security_status: number;

    /**
     * stargates array
     */
    stargates: Array<number>;

    /**
     * system_id integer
     */
    system_id: number;

}
