/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 200 ok object
 */
export interface GetUniverseStationsStationIdOk {
    /**
     * max_dockable_ship_volume number
     */
    max_dockable_ship_volume: number;

    /**
     * name string
     */
    name: string;

    /**
     * office_rental_cost number
     */
    office_rental_cost: number;

    /**
     * ID of the corporation that controls this station
     */
    owner?: number;

    position?: models.GetUniverseStationsStationIdPosition;

    /**
     * race_id integer
     */
    race_id?: number;

    /**
     * reprocessing_efficiency number
     */
    reprocessing_efficiency: number;

    /**
     * reprocessing_stations_take number
     */
    reprocessing_stations_take: number;

    /**
     * services array
     */
    services: Array<GetUniverseStationsStationIdOk.ServicesEnum>;

    /**
     * station_id integer
     */
    station_id: number;

    /**
     * The solar system this station is in
     */
    system_id: number;

    /**
     * type_id integer
     */
    type_id: number;

}
export namespace GetUniverseStationsStationIdOk {
    export enum ServicesEnum {
        BountyMissions = <any> 'bounty-missions',
        AssasinationMissions = <any> 'assasination-missions',
        CourierMissions = <any> 'courier-missions',
        Interbus = <any> 'interbus',
        ReprocessingPlant = <any> 'reprocessing-plant',
        Refinery = <any> 'refinery',
        Market = <any> 'market',
        BlackMarket = <any> 'black-market',
        StockExchange = <any> 'stock-exchange',
        Cloning = <any> 'cloning',
        Surgery = <any> 'surgery',
        DnaTherapy = <any> 'dna-therapy',
        RepairFacilities = <any> 'repair-facilities',
        Factory = <any> 'factory',
        Labratory = <any> 'labratory',
        Gambling = <any> 'gambling',
        Fitting = <any> 'fitting',
        Paintshop = <any> 'paintshop',
        News = <any> 'news',
        Storage = <any> 'storage',
        Insurance = <any> 'insurance',
        Docking = <any> 'docking',
        OfficeRental = <any> 'office-rental',
        JumpCloneFacility = <any> 'jump-clone-facility',
        LoyaltyPointStore = <any> 'loyalty-point-store',
        NavyOffices = <any> 'navy-offices',
        SecurityOffices = <any> 'security-offices'
    }
}
