/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.4.2.dev11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * label object
 */
export interface PostCharactersCharacterIdMailLabelsLabel {
    /**
     * Hexadecimal string representing label color, in RGB format 
     */
    color?: PostCharactersCharacterIdMailLabelsLabel.ColorEnum;

    /**
     * name string
     */
    name: string;

}
export namespace PostCharactersCharacterIdMailLabelsLabel {
    export enum ColorEnum {
        Ffffff = <any> '#ffffff',
        Ffff01 = <any> '#ffff01',
        Ff6600 = <any> '#ff6600',
        Fe0000 = <any> '#fe0000',
        _9a0000 = <any> '#9a0000',
        _660066 = <any> '#660066',
        _0000fe = <any> '#0000fe',
        _0099ff = <any> '#0099ff',
        _01ffff = <any> '#01ffff',
        _00ff33 = <any> '#00ff33',
        _349800 = <any> '#349800',
        _006634 = <any> '#006634',
        _666666 = <any> '#666666',
        _999999 = <any> '#999999',
        E6e6e6 = <any> '#e6e6e6',
        Ffffcd = <any> '#ffffcd',
        _99ffff = <any> '#99ffff',
        Ccff9a = <any> '#ccff9a'
    }
}
