export * from './AllianceApi';
import { AllianceApi } from './AllianceApi';
export * from './AssetsApi';
import { AssetsApi } from './AssetsApi';
export * from './BookmarksApi';
import { BookmarksApi } from './BookmarksApi';
export * from './CalendarApi';
import { CalendarApi } from './CalendarApi';
export * from './CharacterApi';
import { CharacterApi } from './CharacterApi';
export * from './ClonesApi';
import { ClonesApi } from './ClonesApi';
export * from './ContactsApi';
import { ContactsApi } from './ContactsApi';
export * from './CorporationApi';
import { CorporationApi } from './CorporationApi';
export * from './DogmaApi';
import { DogmaApi } from './DogmaApi';
export * from './FittingsApi';
import { FittingsApi } from './FittingsApi';
export * from './FleetsApi';
import { FleetsApi } from './FleetsApi';
export * from './IncursionsApi';
import { IncursionsApi } from './IncursionsApi';
export * from './IndustryApi';
import { IndustryApi } from './IndustryApi';
export * from './InsuranceApi';
import { InsuranceApi } from './InsuranceApi';
export * from './KillmailsApi';
import { KillmailsApi } from './KillmailsApi';
export * from './LocationApi';
import { LocationApi } from './LocationApi';
export * from './LoyaltyApi';
import { LoyaltyApi } from './LoyaltyApi';
export * from './MailApi';
import { MailApi } from './MailApi';
export * from './MarketApi';
import { MarketApi } from './MarketApi';
export * from './OpportunitiesApi';
import { OpportunitiesApi } from './OpportunitiesApi';
export * from './PlanetaryInteractionApi';
import { PlanetaryInteractionApi } from './PlanetaryInteractionApi';
export * from './RoutesApi';
import { RoutesApi } from './RoutesApi';
export * from './SearchApi';
import { SearchApi } from './SearchApi';
export * from './SkillsApi';
import { SkillsApi } from './SkillsApi';
export * from './SovereigntyApi';
import { SovereigntyApi } from './SovereigntyApi';
export * from './UniverseApi';
import { UniverseApi } from './UniverseApi';
export * from './UserInterfaceApi';
import { UserInterfaceApi } from './UserInterfaceApi';
export * from './WalletApi';
import { WalletApi } from './WalletApi';
export * from './WarsApi';
import { WarsApi } from './WarsApi';
export const APIS = [AllianceApi, AssetsApi, BookmarksApi, CalendarApi, CharacterApi, ClonesApi, ContactsApi, CorporationApi, DogmaApi, FittingsApi, FleetsApi, IncursionsApi, IndustryApi, InsuranceApi, KillmailsApi, LocationApi, LoyaltyApi, MailApi, MarketApi, OpportunitiesApi, PlanetaryInteractionApi, RoutesApi, SearchApi, SkillsApi, SovereigntyApi, UniverseApi, UserInterfaceApi, WalletApi, WarsApi];
